### ISSUE TITLE
README doesn't contain information about this project

### ISSUE THREAD

**Issue by SilasReinagel** [tomizechsterson/chargen-ui#28]
It seems to be a template carryover from Create React App.

**Comment by tomizechsterson** [comment]
It is, and it's got information that I sometimes refer to. I intend to someday go through a few articles and get these readme's all pretty:

- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
- https://dbader.org/blog/write-a-great-readme-for-your-github-project
- https://coderwall.com/p/fy05hq/how-to-make-beautiful-github-readme

I've been so focused on getting this project done, I haven't had time to do this yet
